### ISSUE TITLE
这是要全部开源么？

### ISSUE THREAD

**Issue by virusdefender** [WPH95/CodeVS#6]
> CodeVS Open
> 
> CodeVS 开源 Online Judge，前后端分离，Restful API， 有完善的 API 文档，交互友好的前端界面（会有 Html ， Vue， React 三版）
> 预计 16 年寒假上 Github

😊

**Comment by wph95** [comment]
之后 CodeVS 会有 社区版 和 商用版，前者全部开源：）

**Comment by virusdefender** [comment]
期待~~
